apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    port: {{$.Values.deploy_port}}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  loadBalancerIP: {{pluck $.Values.global.env .Values.loadBalancerIP | first | default .Values.loadBalancerIP._default}}